Repository GrayC9/URL-Shortener, pull requests merged in 2024-07, with the labels that each got.

#13 I5/bug short link
  cmd/main.go
  internal/config/config.go
  internal/handlers/handlers.go
  internal/storage/storage.go
Labels: bug

#11 web-ui and address correct
  internal/cmd/main.go
  internal/config/config.go
  internal/handlers/handlers.go
  internal/storage/storage.go
  internal/web/index.html
  internal/web/style.css
Labels: Upgrage

#15 I8/accsess counter
  internal/handlers/handlers.go
  internal/storage/storage.go
  schema/urls.sql
Labels: Upgrage

#16 I9/address data
  internal/handlers/handlers.go
  internal/shortener/shortener.go
  internal/storage/storage.go
Labels: Upgrage

#28 dockerfile create
  deploy/Dockerfile
Labels: enhancement

#25 i21 auth creat
  Makefile
  cmd/main.go
  go.mod
  go.sum
  internal/auth/auth.go
  internal/config/config.go
  internal/storage/storage.go
  internal/web/index.html
  readme.md
  schema/urls.sql
Labels: Upgrage
